module MCP::Protocol
  ToolsList              = "tools/list"
  ToolsCall              = "tools/call"
  PromptsList            = "prompts/list"
  PromptsGet             = "prompts/get"
  ResourcesList          = "resources/list"
  ResourcesRead          = "resources/read"
  ResourcesTemplatesList = "resources/templates/list"
  ResourcesSubscribe     = "resources/subscribe"
  ResourcesUnsubscribe   = "resources/unsubscribe"
  RootsList              = "roots/list"
  Ping                   = "ping"
  LoggingSetLevel        = "logging/setLevel"
  CompletionComplete     = "completion/complete"
  SamplingCreateMessage  = "sampling/createMessage"
  ElicitationCreate      = "elicitation/create"
  Initialize             = "initialize"
  TasksGet               = "tasks/get"
  TasksList              = "tasks/list"
  TasksCancel            = "tasks/cancel"
  TasksResult            = "tasks/result"

  NotificationsToolsListChanged     = "notifications/tools/list_changed"
  NotificationsPromptsListChanged   = "notifications/prompts/list_changed"
  NotificationsResourcesListChanged = "notifications/resources/list_changed"
  NotificationsResourcesUpdated     = "notifications/resources/updated"
  NotificationsRootsListChanged     = "notifications/roots/list_changed"
  NotificationsMessage              = "notifications/message"
  NotificationsInitialized          = "notifications/initialized"
  NotificationsProgress             = "notifications/progress"
  NotificationsCancelled            = "notifications/cancelled"
  NotificationsElicitationComplete  = "notifications/elicitation/complete"
end
